---
# Documentation generation for coffeesprout.users

- name: Ensure documentation directory exists
  file:
    path: "{{ doc_output_dir }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false
  run_once: false

- name: Generate users markdown documentation
  template:
    src: docs/users.md.j2
    dest: "{{ doc_output_dir }}/{{ inventory_hostname }}/users.md"
    mode: '0644'
  delegate_to: localhost
  become: false

- name: Generate users JSON documentation
  template:
    src: docs/users.json.j2
    dest: "{{ doc_output_dir }}/{{ inventory_hostname }}/users.json"
    mode: '0644'
  delegate_to: localhost
  become: false
  when: doc_format in ['both', 'json']
