---

- debug:
    var: ansible_os_family
  tags:
  - always

- name: ensure OS specifics are included
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
  - always

- name: create users
  include_tasks: user.yml
  vars:
    _user: "{{ item }}"
  with_items:
  - "{{ users }}"
  tags:
  - users
  - authorized_keys

- name: manage sudo for users
  template:
    src: managed.j2
    dest: "{{ users_sudoersd_file }}"
    validate: 'visudo -cf %s'
  tags:
  - users
  - sudo

- name: Generate documentation
  include_tasks: documentation.yml
  when: doc_generate | default(true)
  tags:
    - docs
    - documentation
