---
# tasks file for coffeesprout.users

- name: setup users {{ _user.name }}
  user:
    name: "{{ _user.name }}"
    group: "{{ _user.group | default(omit) }}"
    system: "{{ _user.system | default(omit) }}"
    shell: "{{ _user.shell | default(omit) }}"
    home: "{{ _user.home | default(omit) }}"
    password: "{{ _user.password | default(omit) }}"
  tags:
  - users

- name: setup authorized_keys for {{ _user.name }}
  authorized_key:
    user: "{{ _user.name }}"
    state: present
    key: "{{ _user.key }}"
  when: '_user.key is defined'
  tags:
  - authorized_keys

- name: setup authorized_keys from pub in files for {{ _user.name }}
  authorized_key:
    user: "{{ _user.name }}"
    state: present
    key: "{{ lookup('file', _user.name+'.pub') }}"
  when: '_user.key is not defined and _user.ssh'
  tags:
  - authorized_keys
