---
# tasks file for coffeesprout.users

- name: setup users {{ _user.name }}
  user:
    name: "{{ _user.name }}"
    group: "{{ _user.group | default(omit) }}"
    groups: "{{ _user.groups | default(omit) }}"
    append: "{{ _user.append | default(omit) }}"
    uid: "{{ _user.uid | default(omit) }}"
    system: "{{ _user.system | default(omit) }}"
    shell: "{{ _user.shell | default(omit) }}"
    home: "{{ _user.home | default(omit) }}"
    create_home: "{{ _user.create_home | default(omit) }}"
    comment: "{{ _user.comment | default(omit) }}"
    expires: "{{ _user.expires | default(omit) }}"
    password: "{{ _user.password | default(omit) }}"
    state: "{{ _user.state | default(omit) }}"
    remove: "{{ _user.remove | default(omit) }}"
  tags:
  - users

- name: setup authorized_keys for {{ _user.name }}
  authorized_key:
    user: "{{ _user.name }}"
    state: "{{ _user.state | default(omit) }}"
    key: "{{ _user.key }}"
    key_options: "{{ _user.key_options | default(users_default_key_option) | default(omit) }}"
    path: "{{ _user.pubkey_location | default(users_pubkey_location) | default(omit) }}"
    manage_dir: "{{ not ((users_pubkey_location is defined) or (_user.pubkey_location is defined)) }}"
  when:  '_user.key is defined'
  tags:
  - authorized_keys
  ignore_errors: true

- name: setup authorized_keys from pub in files for {{ _user.name }}
  authorized_key:
    user: "{{ _user.name }}"
    state: "{{ _user.state | default(omit) }}"
    key: "{{ lookup('file', _user.name+'.pub') }}"
    key_options: "{{  _user.key_options | default(users_default_key_option) | default(omit) }}"
    path: "{{ _user.pubkey_location | default(users_pubkey_location) | default(omit) }}"
    manage_dir: "{{ not ((users_pubkey_location is defined)  or (_user.pubkey_location is defined)) }}"
  when: '_user.key is not defined and (_user.ssh | default(False))'
  tags:
  - authorized_keys
  ignore_errors: true

- name: write protect keys
  file:
    path: "{{ _user.pubkey_location | default(users_pubkey_location) | default('/home/'+_user.name+'/.ssh/authorized_keys') }}"
    mode: '0400'
    state: file
  when: '(users_pubkey_location is defined)  or (_user.pubkey_location is defined) or (_user.lock_key | default(False))'
