---
- name: Prepare Debian
  hosts: debian*-users
  become: true
  gather_facts: false

  tasks:
    - name: Update package cache (Debian)
      raw: "apt-get update"

    - name: Install Python and packages (Debian)
      raw: "apt-get install -y python3 sudo openssh-client"

    - name: Gather facts
      setup:

- name: Prepare AlmaLinux 9
  hosts: alma9-users
  become: true
  gather_facts: false

  tasks:
    - name: Install Python and packages (AlmaLinux 9)
      raw: "dnf install -y python3 sudo openssh-clients"

    - name: Gather facts
      setup:

- name: Prepare AlmaLinux 8
  hosts: alma8-users
  become: true
  gather_facts: false

  tasks:
    - name: Install Python 3.11 and packages (AlmaLinux 8)
      raw: "dnf install -y python3.11 sudo openssh-clients && alternatives --set python3 /usr/bin/python3.11"

    - name: Gather facts
      setup:

- name: Create test groups on all hosts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Create developers group for testing
      group:
        name: developers
        state: present

    - name: Create testgroup for custom group testing
      group:
        name: testgroup
        state: present

    - name: Create system group for system user testing
      group:
        name: sysgroup
        system: true
        state: present